name: Build Docker Image

on: 
  push: 
    branches: 
      - main 

jobs:

  build-and-push:
    name: Build, push and deploy Docker image to Container Registry 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v2
       
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: kacestudio/deployer-demo:latest

  deploy:
    name: Deploy to OCI Compute VM via SSH action 
    needs: build-and-push
    runs-on: ubuntu-latest
    steps: 
      - name: Executing remote ssh commands using password 
        uses: appleboy/ssh-action@v0.1.4
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd deployer-demo
            docker compose down 
            docker compose pull 
            docker compose up -d 
            docker compose ps

